<a href="https://colab.research.google.com/github/bogdan-l-2000/2d-shooter-game/blob/main/tensorsInPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# To create a tensor, just put a list
a = torch.tensor([1, 2, 3])
print(a)

# Shape is 3: we have a vector of 3 values

print(a.ndim) #1

print(a.dtype) #uint 64.

# Torch looks at the value: if any of the values were a floating point, the type will be float32

# Can specify dtype: a = torch.tensor([1, 2, 3], dtype=torch.float32)

# Creating a tensor for a large number of values: tedius! Need to provide a large list of values, and convert it to a tensor

tensor([1, 2, 3])
1
torch.int64


In [ ]:
# Idea: create a tensor with only zeros

b = torch.zeros(3, dtype=torch.float32)
print(b)

# We can add as many zeroes as possible

b2 = torch.zeros(10, dtype=torch.float32)
print(b2)

b3 = torch.zeros([10, 10], dtype=torch.float32)
print(b3)

b4 = torch.zeros([3, 3, 3], dtype=torch.float32)
print(b4)

b5 = torch.ones([10, 10], dtype=torch.float32)
print(b5)

b6 = torch.rand([3, 3, 3], dtype=torch.float32)
print(b6)

# 3 types normally: zeros, ones, and random values

tensor([0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1.,

In [ ]:
# We can load tensors from images

from PIL import Image

img = Image.open('cat.jpg')

# PIL image: have to convert it to a tensor

# torch.as_tensor(img) # will not work directly: cannot infer dtype of JpegImageFile

# Pytorch: converts numpy arrays into tensors but does not convert images

import numpy as np
c = torch.as_tensor(np.array(img))

# Now, instead of the image, we see the RGB values, stored in a 3-dimensional tensor.

print(c.shape)
# height, width, number of channels

# dtype: uint8

FileNotFoundError: [Errno 2] No such file or directory: 'cat.jpg'

In [ ]:
# Basic operations for tensors

a = torch.arange(10)
b = torch.ones(10)
print(a)
print(b)

print(a + b) # add two tensors
# Can perform multiplication, subtraction, division, power

print(a ** (2*b))


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])


In [ ]:
# Scenario: 2 tensors with different shapes:
a = torch.rand(4)
b = torch.rand(5)
print(a + b)
# Error

# Exception: broadcasting, allows to add tensors of different shapes and sizes, under very specific circumstances

In [ ]:
# Tensors: you can add together a lot of numbers efficiently

a = torch.rand(1_000_000)
b = torch.rand(1_000_000)
c = a + b

In [ ]:
%timeit c = a + b

2.19 ms ± 35.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# Pytorch itself is heavily optimized and a sort of language that allows you to quickly offload computation onto a GPU

# Take a, b, put them to the GPU

a_gpu = a.to('cuda')
b_gpu = b.to('cuda')

%timeit a_gpu + b_gpu

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
# Manipulating tensors and their shapes

a = torch.arange(6)
print(a)
print(a.shape)
print(a.view(2, 3)) # Keep the values around, but change the shape
# 2 functions here: view and reshape

# View: does not copy the underlying data: simply changes the shape
# Reshape: copies the underlying data

tensor([0, 1, 2, 3, 4, 5])
torch.Size([6])


In [ ]:
# Next: basic linear algebra

a = torch.rand(2, 3)
print(a)
print(a.mT) # matrix transpose.

tensor([[0.1359, 0.8862, 0.2303],
        [0.7542, 0.0428, 0.4515]])
tensor([[0.1359, 0.7542],
        [0.8862, 0.0428],
        [0.2303, 0.4515]])


In [ ]:
a = torch.rand(2, 3, 4)
print(a) # 2 matrices of lists 3 * 4

# Permute: swaps any dimension
print(a.permute(1, 2, 0).shape)
print(a.permute(1, 2, 0))
# data in the 2nd dimension is now stored in the first dimension
# Data in the 3rd dimension is now stored in the second dimension
# data stored in the 1st dimension is now in the last dimension

# Helpful for loading images or other data that is rearranged, and helps such that deep networks can process it
# In the input to the deep network, you will see permutations of your data that you can feed in to the network

tensor([[[2.3477e-01, 3.8751e-01, 1.6804e-01, 9.6074e-01],
         [4.3840e-01, 5.2607e-01, 2.4063e-01, 5.3420e-02],
         [7.9954e-01, 5.4937e-01, 3.3027e-01, 9.5531e-01]],

        [[7.5224e-01, 7.0088e-01, 3.4458e-01, 2.6722e-01],
         [9.9354e-01, 9.2643e-04, 7.0850e-01, 7.6592e-01],
         [1.6477e-02, 6.5195e-01, 6.2068e-01, 1.7950e-01]]])
torch.Size([3, 4, 2])


In [ ]:
# Add, subtract dimensions

a = torch.arange(6)
print(a[None])
print(a[None].shape)


# Creates a singleton dimension, so we add one of size one, where we specify a none


# Add the None to the end:
print(a[:, None].shape)

# Add a None to the start and end of the data
print(a[None, :, None].shape)

# Colon: your first sort of dimension that you're looking at

# Additional dimensions of size one can be viewed anywhere

print(a[..., None].shape) # ... if you don't know the number of dimensions

print(a[..., None, :, None].shape) # : is the last dimension


tensor([[0, 1, 2, 3, 4, 5]])
torch.Size([1, 6])
torch.Size([6, 1])
torch.Size([1, 6, 1])
torch.Size([6, 1])
torch.Size([1, 6, 1])


In [ ]:
# We can remove dimensions from a tensors as long as it is of size one

a = torch.arange(6).view(3, 2, 1, 1)
print(a[..., 0].shape)

print(a.squeeze(-1).shape) # Remove last dimension
print(a.squeeze(-2).shape) # remove second last dimension

# Cannot squeeze first dimension, because it is not size one

# Squeeze with no arguments: remove all dimensions
# Dangerous! Never use it. You may remove data that you would want.

torch.Size([3, 2, 1])
torch.Size([3, 2, 1])
torch.Size([3, 2, 1])


In [ ]:
# Specific concept on how to add tensors that don't quite have the same shape.

# a = torch.rand(4)
# b = torch.rand(5)

# print(a + b) # error

# If mismatch is between dimensions of size 1, we can add tensors together

a = torch.rand(4)
b = torch.rand(1)

print(a + b) # this works

# Interesting concept: we can increase the dimensions of the tensor

a = torch.rand((4, 1))
b = torch.rand((1, 5))
print(a + b) # this works

# This is known as broadcasting: what PyTorch does internally, it says to take a tensor of size 4 * 1, and add a 1 * 5 tensor to it
# Replicate this above tensor, replicate it 5 times
# replicate bottom one 4 times, and add them together

# Powerful concept: complex mathematical calculations are in a small form

a = torch.arange(4).view(4, 1)
b = torch.arange(5).view(1, 5) * 10

print(f'{a = }')
print(f'{b = }')
print(a * b) # This is like the outer product

# Create a big output matrix like this

# Broadcasting allows us to express any operation that we can fit into the right shapes
# Any element-wise operation applies to all possible elements


tensor([1.1853, 1.5384, 1.1239, 0.8252])
tensor([[0.2514, 0.2648, 0.3271, 0.7859, 0.3392],
        [0.2548, 0.2682, 0.3305, 0.7893, 0.3426],
        [0.8546, 0.8680, 0.9303, 1.3891, 0.9424],
        [0.6191, 0.6325, 0.6948, 1.1536, 0.7069]])
a = tensor([[0],
        [1],
        [2],
        [3]])
b = tensor([[ 0, 10, 20, 30, 40]])


In [ ]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)

# distance between all pairs of random numbers

# without broadcasting:
for i in range(10):
  for j in range(10):
    d[i, j] = (x[i] - x[j]).pow(2).sum()
print(d) # Diagonal is zero
# This is not very efficient, tedious to write and not the easiest to read


# Using broadcasting:
# add a singleton dimension, take x, add the one in the first position
# This subtracts any row of X from any other row of x
# Take the suqre elements, and sum along the last dimension (the dimension along the channels of X)

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1) # Compact way to write complex notation
print(d)

tensor([[0.0000, 4.0098, 4.7173, 4.5537, 1.3656, 0.1455, 0.8941, 6.1134, 5.1113,
         1.8436],
        [4.0098, 0.0000, 0.0338, 0.0177, 0.7338, 3.3536, 7.8472, 0.7806, 2.3419,
         0.4535],
        [4.7173, 0.0338, 0.0000, 0.0102, 1.0291, 4.0419, 8.8902, 0.8248, 2.7022,
         0.6836],
        [4.5537, 0.0177, 0.0102, 0.0000, 0.9790, 3.8321, 8.5608, 0.6792, 2.3820,
         0.6493],
        [1.3656, 0.7338, 1.0291, 0.9790, 0.0000, 1.1442, 4.1412, 2.3166, 3.0013,
         0.0360],
        [0.1455, 3.3536, 4.0419, 3.8321, 1.1442, 0.0000, 0.9475, 4.7928, 3.6059,
         1.5532],
        [0.8941, 7.8472, 8.8902, 8.5608, 4.1412, 0.9475, 0.0000, 9.4613, 6.7102,
         4.9101],
        [6.1134, 0.7806, 0.8248, 0.6792, 2.3166, 4.7928, 9.4613, 0.0000, 0.8710,
         1.9285],
        [5.1113, 2.3419, 2.7022, 2.3820, 3.0013, 3.6059, 6.7102, 0.8710, 0.0000,
         2.8699],
        [1.8436, 0.4535, 0.6836, 0.6493, 0.0360, 1.5532, 4.9101, 1.9285, 2.8699,
         0.0000]])
tensor([[

In [ ]:
x = torch.randn(10, 2)
d = torch.zeros(10, 10)

# Now: want the maximum distance
max_dist, max_idx = 1e100, (-1, -1)
# without broadcasting:
for i in range(10):
  for j in range(10):
    if (x[i] - x[j]).pow(2).sum() > max_dist:
      max_dist, max_idx = (x[i] - x[j]).pow(2).sum(), (i, j)
print(max_dist, max_idx)

# In pytorch: compute the pairwise distance using broadcasting, then compute the maximum value and the argmax out of it

d = (x[:, None, :] - x[None, :, :]).pow(2).sum(-1) # Compact way to write complex notation
print(d.max(), (d.argmax() // 10, d.argmax() % 10))

# Caveat: argmax flattens the array first, and then computes the distance


# using tensors is a lot easier



1e+100 (-1, -1)
tensor(4.6646) (tensor(6), tensor(8))


In [ ]:
# Examples of matrices

a = torch.rand(2, 4)
b = torch.rand(4, 3)
c = a @ b # Matrix multiplication, like numpy
print(c.shape) # 2 * 3

# Same concept with vectors

a = torch.rand(2, 4)
b = torch.rand(4)
c = a @ b
print(c.shape) # 2
d = b @ a.mT
print(d.shape)

# norm
print(b.pow(2).sum().sqrt())
print(torch.linalg.norm(b))


#Pytorch: allows you to create tensors, manipulate them, reshape them, combine them in concise notation

torch.Size([2, 3])
torch.Size([2])
torch.Size([2])
tensor(1.2000)
tensor(1.2000)
